- hosts: all
  become: yes

  tasks:
    - name: Create a folder to kube config archive
      shell: mkdir -p ~/.kube
    
    - name: Config access to kubecluster
      shell: bash -c "$(oci ce cluster create-kubeconfig --cluster-id ocid1.cluster.oc1.sa-saopaulo-1.aaaaaaaaeihgfykrglfbwvrlzlq4wekqgoinq7jh4lpnceceyc66rykhz2jq --file $HOME/.kube/config --region sa-saopaulo-1 --token-version 2.0.0)"

    - name: Set kubeconfig environment
      shell: export KUBECONFIG=$HOME/.kube/config
