name: Terraform Pipeline
on:
  push:
    branches:
      - main
jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.4
    - name: Validate Terraform
      run: |
        cd terraform
        terraform init
        terraform validate
    - name: Terraform Plan
      run: |
        cd terraform
        terraform init
        terraform plan
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        cd terraform
        terraform init
        terraform apply -auto-approve
